spring.application.name=auth-service

spring.config.import=optional:configserver:http://localhost:8888


logging.level.root=INFO
logging.level.com.imspos.auth_service=DEBUG
logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
