spring.application.name=auth-service

spring.config.import=optional:configserver:http://localhost:8888

eureka.client.service-url.defaultZone= http://localhost:8761/eureka

spring.security.enabled=false
spring.security.authorization.enabled=false

logging.level.root=INFO
logging.level.com.imspos.auth_service=DEBUG
logging.file.name=logs/application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
