spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Enable service discovery for routing
spring.cloud.discovery.locator.enabled=true
spring.cloud.discovery.locator.lower-case-service-id=true

# Manual route config
#spring.cloud.gateway.routes[0].id=auth-service
#spring.cloud.gateway.routes[0].uri=lb://auth-service
#spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
